### ISSUE TITLE
Not able to configure fluentd to route all logs to a log sink

### ISSUE THREAD

**Issue by muratcanozdemir** [kube-logging/logging-operator#1009]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
I use the default clusterflow and clusteroutput to forward all my logs to a loki instance in my cluster with multiple nodes. Depending on where the pods are deployed, if loki and fluentd deploy on the same node, then I can see logs coming from the pods in that node, but any mismatch and I don't have any logs showing up in loki

**Expected behaviour**:
A concise description of what you expected to happen.
Clusterflow and clusteroutput in their default configuration should collect all logs to a log sink.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.
- Use a kubernetes cluster with at least two nodes, always check which node the pods are deployed
- Deploy the logging operator as is
- Deploy logging-operator-logging with the most generic Log Sink as loki:
- Deploy loki as well, and reference the url properly
`clusterFlows:
    - name: loki
      spec:
        match:
          - select: {} 
        globalOutputRefs:
          - loki

  clusterOutputs:
    - name: loki
      spec:
        loki:
          url: http://loki:3100
          configure_kubernetes_labels: true
          buffer:
            timekey: 1m
            timekey_wait: 30s
            timekey_use_utc: true`
- Wait for a while as loki collects all the logs

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AKS and EKS
- logging-operator version (e.g. 2.1.1): 3.17.4
- Install method (e.g. helm or static manifests): Both helm and manifests
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
@muratcanozdemir Does this issue still exist?

**Comment by ProfMoo** [comment]
> @muratcanozdemir Does this issue still exist?

@pepov Hi! I know it's been a long time, but I'm also seeing this exact behavior. Hopefully we can figure out a solid solution here 😄.

**Overview**

My current setup is a homelab Kubernetes cluster, running on a server rack at home. I use Proxmox to spin up Talos VMs. For logging, I use the Logging Operator to send logs to Loki.

My Logging Operator is deployed via the Helm chart (Helm chart version `4.6.0`) using Flux. The values and version(s) are defined [here](https://github.com/ProfMoo/home/blob/b81e747a2e2f8a4a53dfc4292a1832e8a8680698/kubernetes/homelab/observability/logging-operator/app/helmrelease.yaml#L31-L96).

Loki is also deployed via Helm and Flux (Helm chart version `5.47.1`). The values and version(s) are defined [here](https://github.com/ProfMoo/home/blob/b81e747a2e2f8a4a53dfc4292a1832e8a8680698/kubernetes/homelab/observability/loki/app/helmrelease.yaml#L31-L81).

**Behavior**

Initially, I have just one Fluentd replica. Loki and Fluentd were on different k8s nodes. Fluentd would connect to Loki (verified via the logs) and the buffer would hover around 200MB, perhaps slowly going down. However, I was unable to get logs to show up in Grafana.

I increased the Fluentd replicas to 2, and thankfully the new Fluentd pod landed on the same node as Loki. Then, logs began truly flowing into Loki and I could view the logs in Grafana.

Perhaps the weirdest part was there were no error messages (and the buffer would often shrink) when Loki and Fluentd were on different nodes.

Happy to help debug this one, please let me know if you need any additional information.

**Comment by pepov** [comment]
Hey @ProfMoo !

A few questions:

- I've seen loki (with a standalone config like yours) not accepting a client for the first time and then get stuck in that state. have you tried restarting the first pod to see if it can connect the second or third time?
- I can see you have configured `reject_old_samples` but do you also have a host related index(label) so that we can truly eliminate the possibility of out-of-order writes? I beleive there should be a host field when `configure_kubernetes_labels` is enabled but can you please check in loki if you have it or not?
- can you verify you have no such behaviour when you try the same with a different application?
- how about using the fqdn for the loki service like `loki.observability.svc.cluster.local.:3100`
