### ISSUE TITLE
Make File output configurable

### ISSUE THREAD

**Issue by xhejtman** [kube-logging/logging-operator#1010]
**Is your feature request related to a problem? Please describe.**
In the current logging-operator, `file` output is always present and possible to use. Being an admin of a cluster, I do not want users to use the `file` output as it stores logs into the fluend container without filtering output path, not sure if you can actually set path different to `/tmp` or not. I would like to make the `file` output optional, e.g., via values in charts. I see that I can mount PVC into `/tmp` but I would like to see this output completely disabled.

**Comment by aslafy-z** [comment]
I'm doing this using [Kyverno policies](https://kyverno.io/), the same thing can also be achieved with [Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/). I doubt we'll implement that kind of limitation in the product itself. What do you think @pepov @ahma?

**Comment by xhejtman** [comment]
Isn't it a bit overkill, if you can do simple `if` in the helm chart, to not define the `file` item in the CRD?
