### ISSUE TITLE
volumeMountChmod  failing with error chmod: /buffers: Operation not permitted

### ISSUE THREAD

**Issue by sureshgoli25** [kube-logging/logging-operator#1030]
While trying to use the parameter volumeMountChmod  in fluentd spec to increase the number of workers. We started seeing the init Container is failing with error.

It seems the command `chmod -R 777 /buffers` in initContainer `volume-mount-hack` is running as nonRoot. 

Below are the only logs we see of initContainer.

`
chmod: /buffers: Operation not permitted
chmod: /buffers: Operation not permitted
`
/buffers is PVC backed mount point.

Is there any way to pass initcontainer configuration via logging CRD?

**Comment by sureshgoli25** [comment]
Any pointers would definitely helps.

**Comment by pepov** [comment]
`volumeMountChmod` was a hack that shouldn't be used anymore. You should be able to configure workers without that feature, since `fsGroup` is automatically configured in the fluentd pod's securityContext
