### ISSUE TITLE
Support new Elasticsearch "composable" index template format

### ISSUE THREAD

**Issue by johnlane** [kube-logging/logging-operator#1034]
**Is your feature request related to a problem? Please describe.**

I am using the logging operator (helm chart) version 3.17.7 with the Elasticsearch output plugin for Fluentd. It would seem that it uses the deprecated Elastic [legacy index template](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/indices-templates-v1.html) rather than the newer [composable index templates](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/index-templates.html).

The problem is that I have is that it does not appear to be possible to configure the logging operator to use the newer composable index templates.

I've written this as a feature request because I am able to use the logging operator with legacy templates fine, so this isn't a bug. However **legacy templates are deprecated** so a way of using the composable templates is desirable.

Although the plugin supports a [use_legacy_template](https://github.com/uken/fluent-plugin-elasticsearch#use_legacy_template) switch this does not appear to be recognised by the CRD `io.banzaicloud.logging.v1beta1.ClusterOutput.spec.elasticsearch` (it's documented in the plugin but not on the [logging operator plugin page](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch)).

There is a warning output to the fluentd log about the deprecation
```
fluentd warning: 299 Elasticsearch-7.13.2-4d960a0733be83dd2543ca018aa4ddc42e956800 "Legacy index templates are deprecated in favor of composable templates."
```

**Describe the solution you'd like**

I would like to be able to add `use_legacy_template: false` to the Elasticsearch output spec so that the plugin works with composable index templates.

**Describe alternatives you've considered**

I did try to add `use_legacy_template: false` to a `clusterOutput` spec anyway:

```
# clusteroutputs.logging.banzaicloud.io "elasticsearch" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(ClusterOutput.spec.elasticsearch): unknown field "use_legacy_template" in io.banzaicloud.logging.v1beta1.ClusterOutput.spec.elasticsearch
```

I also manually edited the generated `fluentd.conf` to include this feature and this did change the plugin to use the composable templates. However I didn't follow through with a working configuration because I need to drive it from the logging operator CRD - therefore I can't comment on whether the plugin actually works with composable templates (although I expect it likely does, given that it's documented).

**Comment by johnlane** [comment]
remove stale

**Comment by aslafy-z** [comment]
Hey @johnlane 
Can you please give a go to https://github.com/kube-logging/logging-operator/pull/1441? I published the docker image (based on latest master) at `ghcr.io/aslafy-z/logging-operator:v4.3.0-dev.1`.
