### ISSUE TITLE
Make key_prefix configurable for tag_normaliser

### ISSUE THREAD

**Issue by cjprinse** [kube-logging/logging-operator#1049]
Tag normaliser is only working with the property `format`
However, our logs are decorated with a field `log_channel`. We want to base our tags on this field.

The tag_normaliser plugin supports a property `key_prefix` with a default of `kubernetes`

This is way we can only use field within the kubernetes decoration of the log record.
This is why we cannot use our custom field `log_channel` in the tag.

Is it possible to make the property `key_prefix` configurable in the `tag_normaliser` part of the Flow spec?

Another solution could be setting the default for `key_prefix` to an empty string, so you can reach every field by default. How ever, this would be a breaking change.

**Comment by pepov** [comment]
it's a trivial thing to implement, happy to help if someone wants to take a shot
