### ISSUE TITLE
FluentD kafka Output Set principal and path to keytab for SASL/GSSAPI authentication

### ISSUE THREAD

**Issue by bryce-wilkinson-443** [kube-logging/logging-operator#1058]
**Describe the solution you'd like**
Add support for SASL authentication customization when creating an output using the kafka plugin 
https://github.com/fluent/fluent-plugin-kafka
Out of the box the fluent Kafka plugin provides support for the principal and keytabs. However these parameters are missing from logging operator's CRD 
 

**Additional context**
I would like to use this as our Kafka config utilizes kerberos

**Comment by aslafy-z** [comment]
Implemented with #1059
