### ISSUE TITLE
Send fluentd logs to stdout and make fluent-bit ignore them by default

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1076]
**Is your feature request related to a problem? Please describe.**
Ease fluentd debugging

**Describe the solution you'd like**
To ease debugging of fluentd, send logs to stdout instead of a file.
Exclude them by default from fluent-bit collection.

**Additional context**
Related #1075

**Comment by pepov** [comment]
What would be a good way to implement this? How about having a dedicated label for marking certain pods for fluentbit to drop their messages?

**Comment by aslafy-z** [comment]
Fluentbit has the feature: see the `K8S-Logging.Exclude` option and the associated `fluentbit.io/exclude` annotation. I have it in production right now and its fine :)
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations

**Comment by pepov** [comment]
Created a PR to make the fluentbit side flag enabled by default: https://github.com/kube-logging/logging-operator/pull/1395

Although this is a breaking change in theory, I don't think this would affect anyone negatively in practice. I think this is enough to introduce for now and make the changes on the fluentd side later together with improvements around the fluentd internal log handling.

**Comment by pepov** [comment]
This behaviour is now enabled with 4.3 and logs for fluentd and syslog-ng will be excluded by default in 4.4, so moving the issue to that milestone
