### ISSUE TITLE
Allow option to disable completely fluentbit from logging-operator-logging resource

### ISSUE THREAD

**Issue by Drupi** [kube-logging/logging-operator#1081]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy only Fluentd managed by logging-operator, but even if I don't specify the `.Values.fluentbit` within the `values.yaml` - Helm Template always put `fluentbit: {}`. I tried with pure Logging resource and logging-operator doesn't create fluentbit without declaration. 

**Describe the solution you'd like**
Some kind of switch enable/disable

**Describe alternatives you've considered**
There is an option to not use helm-chart, but if the chart exists, it should support it. 

I'm happy to fire a PR for this, but I would like to talk to someone before. I'm not sure how do you feel about the enabled/disabled switch as it is in TLS setup. 
Everything is about this logic: https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-operator-logging/templates/logging.yaml#L53

**Comment by aslafy-z** [comment]
This looks reasonable to me. WDYT @pepov?

**Comment by pepov** [comment]
Yes, absolutely.
