### ISSUE TITLE
creationTimestamp is not required 

### ISSUE THREAD

**Issue by alibahramian** [kube-logging/logging-operator#1089]
https://github.com/banzaicloud/logging-operator/blob/a50fcc5e0ddd58c8e7a5aff1485d2171d89d3561/charts/logging-operator/templates/clusterrole.yaml#L7

creationTimestamp is not required and it causes errors on CI/CD pipelines

`logging-operator/charts/logging-operator/templates/clusterrole.yaml contains an invalid ClusterRole (release-name-logging-operator) - metadata.creationTimestamp: Invalid type. Expected: string, given: null`

**Comment by aslafy-z** [comment]
Here's the source file https://github.com/banzaicloud/logging-operator/blob/master/config/rbac/role.yaml 
`make manifests` takes care of the helm chart template update
