### ISSUE TITLE
fluentd image: update gelf dependency

### ISSUE THREAD

**Issue by kwinkel** [kube-logging/logging-operator#1090]
### Background
While debugging an issue I've faced an encoding error. We have some multiline log messages exceeding the limit of docker (>16kb) and splitted up into multiple lines. Our application logs it's messages as json itself and this caused some quirks while processing them.

### The issue
There was a FluentD log-message I've found which already is documented at the FluentD docs: https://docs.fluentd.org/quickstart/faq#i-got-encoding-error-inside-the-plugin.-how-to-fix-it
After researching where this error occurs, I've found that gelf dependency is the source of this error. 
Newer versions (3.1.0) as the one being used (3.0.0) have an opt-in to use `yajl` as json parser when available which is recommended by FluentD documenation.

gelf 3.0.0 -> https://github.com/graylog-labs/gelf-rb/blob/v3.0.0/lib/gelf/notifier.rb
gelf 3.1.0 -> https://github.com/graylog-labs/gelf-rb/blob/v3.1.0/lib/gelf/notifier.rb#L5-L9

### My workaround
My workaround was to avoid this conversion error and use a customized image which has a newer version of the gelf dependency (3.1.0) to finally see what the real error was for us.

### Suggested improvement
Please use gelf v3.1.0 instead of v3.0.0.
eg. here https://github.com/banzaicloud/logging-operator/blob/a50fcc5e0ddd58c8e7a5aff1485d2171d89d3561/fluentd-image/v1.14/Dockerfile

**Comment by pepov** [comment]
There is a new image `ghcr.io/kube-logging/fluentd:v1.15-staging` rebased on ruby 3.1.0, which is still experimental but should be a good starting point to test with:
```
docker run --rm -ti --entrypoint sh ghcr.io/kube-logging/fluentd:v1.15-staging -c "gem list | grep gelf"
fluent-plugin-gelf-hs (1.0.8)
gelf (3.1.0)
```
soon this will replace the main v1.15 image which is still running on ruby 2.7
