### ISSUE TITLE
Fluentd detect exceptions filter not able to process logs without kubernetes tag prefix

### ISSUE THREAD

**Issue by petergvizd** [kube-logging/logging-operator#1114]
**Is your feature request related to a problem? Please describe.**
We would like to apply detect exceptions filter to logs that are sent to fluentd, from sources that are not in kubernetes and because of that do not contain `kubernetes.` tag prefix (same applies to `tagnormaliser` filter). 

**Describe the solution you'd like**
Currently in detect exceptions filter there is hardcoded value for both `match` directive and `remove_tag_prefix` parameter https://github.com/banzaicloud/logging-operator/blob/master/pkg/sdk/logging/model/filter/detect_exceptions.go#L98 . Suggested solution is to have option to customise both parameters with default value set to `kubernetes`.
PR for suggested solution https://github.com/banzaicloud/logging-operator/pull/1113

**Comment by pepov** [comment]
fixed in #1113
