### ISSUE TITLE
Add the ability to choose a Service account into values.yaml

### ISSUE THREAD

**Issue by mamu-reply** [kube-logging/logging-operator#1123]
**Is your feature request related to a problem? Please describe.**
I added the logging operator as helm in a terraform that creates the EKS with ArgoCD and different applications/operators, and I made each one use its own service account in order to have the right permissions on AWS.
But I see that the logging-operator and logging-operator-logging helms do not give the possibility to select a service account other than the one that is created automatically.

**Describe the solution you'd like**
At the moment to stem the problem I assigned permissions to the EKS node group, because with my logging operator I could not send the logs to cloudwatch, but it would be more functional if I could tell the logging-operator which service account to use, so as to being able to assign what I created ad hoc with the correct permissions, avoiding giving permissions at the node group level.

**Describe alternatives you've considered**
I tried to create the role with permissions and to assign only the role annotation to the service account which is created automatically, but it doesn't seem to work.

**Comment by pepov** [comment]
this is already implemented in helm chart 4.2.1
