### ISSUE TITLE
Extra volumes for fluent-bit

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1126]
**Is your feature request related to a problem? Please describe.**
Fluentbit has some issues with networking disruptions these times. 

See https://github.com/fluent/fluent-bit/issues/6010
See https://github.com/fluent/fluent-bit/issues/5485

**Describe the solution you'd like**
Ability to add extraVolumes and extraVolumeMounts to fluent-bit daemonsets so I can add a executable liveness probe that detects this behavior and destroy/re-create the pod.

**Describe alternatives you've considered**
Reacting on this event by other ways.
Eg:
- Sidecar (not implemented in Logging Operator)
- Create a child docker image with a script inside
- Trigger job on Alertmanager webhook

**Comment by pepov** [comment]
@aslafy-z I'm not sure how the extra volume helps, but there is already an option to define extra hostPath volume mounts using `extraVolumeMounts`

**Comment by aslafy-z** [comment]
This can be closed. I don't need a extraVolumeMount to overwrite the probe. My bad :)
