### ISSUE TITLE
Add hostname tag to logged messages

### ISSUE THREAD

**Issue by xhejtman** [kube-logging/logging-operator#1133]
Hello,

is there any chance to add hostname tag to collected fluentbit log messages?

Logs from pods could be fixed by parsing host from kubernetes metadata tag, however, if we are collecting logs e.g., from kubelet or other sources that do not have kubernetes metadata, there seems to be no way to additionaly add hostname. 

I believe it would be really usefull to add hostname tag to all messages.

Another issue is that sending fluentd logs GELF (graylog/elastic), all messages have source set to fluentd hostname which is due to operator set to mostly the same value accross many clusters (using rancher, all messages have source set to: `rancher-logging-root-fluentd-0`. It whould be great if there is an option to override this hostname to something better, e.g., custom name.

**Comment by pepov** [comment]
@xhejtman is this still an issue for you? We might want to revisit this

**Comment by xhejtman** [comment]
no, it is not an issue with the lastest operator, I was able to add tags as needed.
