### ISSUE TITLE
Tag_Normaliser require an update

### ISSUE THREAD

**Issue by Drupi** [kube-logging/logging-operator#1159]
**Is your feature request related to a problem? Please describe.**
Current up-stream fluentd image contains tag_normaliser in older version which doesn't support multi-worker setup.

**Describe the solution you'd like**
Rebuild fluentd image with newer version(current: 0.1.1, expected: 0.1.2)

**Comment by pepov** [comment]
this is already fixed with the latest release. From a fluentd container created by logging-operator version 4.0.0
```
/ $ gem list | grep tag-normaliser
fluent-plugin-tag-normaliser (0.1.2)
```
