### ISSUE TITLE
Split fluentd configuration 

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1311]
**Is your feature request related to a problem? Please describe.**
We've hit the 1MB fluentd configuration secret size 

**Describe the solution you'd like**
Automatic split of fluentd configuration into multiple secrets 

**Describe alternatives you've considered**
Shard with multiple Logging instances but it multiplies the node agents

**Comment by pepov** [comment]
Compression of the generated config can be enabled in the logging resource already:
```
spec:
  fluentd:
    compressConfigFile: true
```

Please note that we are also working on a solution to support multiple fluentd deployments with a single fluentbit agent daemonset. I will describe it in more detail in an issue later.
