### ISSUE TITLE
Fluentbit config hot reload 

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1312]
**Is your feature request related to a problem? Please describe.**
Fluentbit restarts can take a long time if there is lot of files to index. 

**Describe the solution you'd like**
Integration of the fluentbit new hot reload feature, see
https://fluentbit.io/announcements/v2.1.0/

**Comment by tarokkk** [comment]
That one is a looong awaited feature ;) and it will help some upcoming features as well
