### ISSUE TITLE
kindly upgrade image for fluentd 

### ISSUE THREAD

**Issue by 3rgfbrgf** [kube-logging/logging-operator#1333]
**Is your feature request related to a problem? Please describe.**
Your image ghcr.io/banzaicloud/fluentd doesn't pass generic security checks because it's based on old vulnerable versions of packets.

**Describe the solution you'd like**
Bump alpine version and fluentd components versions to the latest.

**Describe alternatives you've considered**
Provide security context for critical and high CVE if they are not relevant for the image (f.e. they are not being used by any functionality etc)

**Additional context**
How to reproduce:
scan your image with any tool available. F.e. trivy
`trivy image --scanners vuln --severity critical,high ghcr.io/banzaicloud/fluentd`
you will get a detailed report with fixed versions available.

**Comment by pepov** [comment]
@3rgfbrgf that image is not used anymore.

The current maintained fluentd images are:
- `ghcr.io/kube-logging/fluentd:v1.14` used in logging-operator v4.0.0 and v4.1.0
- `docker pull ghcr.io/kube-logging/fluentd:v1.15` used in master and first candidate for v4.2.0
- `docker pull ghcr.io/kube-logging/fluentd:v1.15-staging` second candidate for logging-operator v4.2.0 or the next after that (contains alpine 3.17.3 and ruby 3.1.0)

I would recommend using the last one and sending us feedback about any issues it has, being it security or functional. I ran the security checks against it and it only found one, I'm going to look at that if I can fix it.

**Comment by pepov** [comment]
I forgot to add, that unfortunately we cannot upgrade the first two images, because later alpine versions have ruby 3 by default, this is why I recommend using the last one.

I created a PR to fix the single vuln trivy reported in it:
https://github.com/kube-logging/fluentd-images/pull/35
