### ISSUE TITLE
Adding Elasticsearch and Splunk Outputs to syslog-ng

### ISSUE THREAD

**Issue by liadlauber** [kube-logging/logging-operator#1339]
Issue Overview:
Currently, syslog-ng lacks support for Elasticsearch and Splunk outputs via the logging-operator. This issue aims to request the addition of these outputs to enhance the functionality and flexibility of syslog-ng.

Feature Request:
I kindly request the development team to extend the logging-operator to include support for Elasticsearch and Splunk outputs. This enhancement would greatly benefit users like me who require seamless integration with Elasticsearch and Splunk for their logging needs.

Expected Behavior:
Upon implementing Elasticsearch and Splunk outputs, syslog-ng, when configured with the logging-operator, should be able to route logs to Elasticsearch and Splunk destinations effortlessly. This functionality would enable users to leverage the power and capabilities of Elasticsearch and Splunk for log analysis and monitoring.

**Comment by mzeevi** [comment]
Hey, has progress been made here? I'm interested in this use-case as well 😄

**Comment by tarokkk** [comment]
Progress in this PR #1362

**Comment by OverOrion** [comment]
Splunk HEC output was implemented in #1457.
