### ISSUE TITLE
fluentd prometheusRule more configurable

### ISSUE THREAD

**Issue by genofire** [kube-logging/logging-operator#1354]
**Is your feature request related to a problem? Please describe.**
It is okay, if just a small count of error or retries happen. Just a big count in short time are eval.

**Describe the solution you'd like**
Make it configurable the threashold of increases (not static 0).

**Describe alternatives you've considered**

**Additional context**
i am talking about this lines:
https://github.com/kube-logging/logging-operator/blob/6472cec6305064c65c9e45e54627bf10aa4efa74/pkg/resources/fluentd/prometheusrules.go#L95-L122

**Comment by pepov** [comment]
thanks for reporting makes sense
