### ISSUE TITLE
The aliyun oss plug-in configuration parameters are incorrect

### ISSUE THREAD

**Issue by xiaoluhong** [kube-logging/logging-operator#1361]
**Describe the bug**:
The documentation (https://kube-logging.dev/docs/configuration/plugins/outputs/oss/) describes the oss plug-in git repo is https://github.com/aliyun/fluent-plugin-oss. In the aliyun oss plug-in usage example, it uses access_key_id and access_key_secret.

However, the following places use aaccess_key_secret，When I set aaccess_key_secret, it will show an error
```
2023-06-14 05:08:47 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="'access_key_secret' parameter is required"
```

- documentation
https://kube-logging.dev/docs/configuration/plugins/outputs/oss/#output-config-aaccess_key_secret

- ogging-operator
https://github.com/kube-logging/logging-operator/blob/3.17.7/pkg/sdk/logging/model/output/oss.go#L60

- clusteroutputs
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml#L4592
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml#L4781
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml#L10673
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml#L10862

- outputs
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml#L4507
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml#L4696
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml#L10582
https://github.com/kube-logging/helm-charts/blob/7c27896bc798b6abce4017b8b8ede7f38443e2f3/charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml#L10771

/kind bug

**Comment by aslafy-z** [comment]
Hello @xiaoluhong 
I made a PR to fix this issue. Can you give a try to `ghcr.io/aslafy-z/logging-operator:aliyun-access-key-secret`? It's based on master.
Thank you

**Comment by xiaoluhong** [comment]
Hi @aslafy-z , 
Sorry, I don't have an environment for testing at the moment. I have done code changes and tests before, I checked the change record, asically the same as your fix. This is my previous commit：https://github.com/xiaoluhong/logging-operator/commit/e9c2b44fb74de5bb02b8ca0599b6fabf3d37ac32#diff-1ad4e8eb78bf4bddf2c452f7d18c79de7d8fd5d61134b251c912bdf0633fbd52

ps: 
For the logging-operator oss to work properly, the oss plug-in name in Dockerfile (https://github.com/kube-logging/fluentd-images/blob/main/v1.14/Dockerfile#L53) also needs to be modified.  The oss plugin should be fluent-plugin-aliyun-oss, not fluent-plugin-oss.
