### ISSUE TITLE
Unable to configure CPU and memory requests and limits for the container 'buffer-metrics-sidecar'

### ISSUE THREAD

**Issue by hankyang1202** [kube-logging/logging-operator#1363]
We are utilizing HPA (Horizontal Pod Autoscaling) with CPU and memory utilization metrics in our setup for auto scaling. However, we encountered an issue related to the configuration of CPU and memory requests and limits for the 'buffer-metrics-sidecar' container.

https://github.com/kube-logging/logging-operator/issues/1231

We have enabled the scaling drain configuration, but we encountered an issue where we are unable to use HPA (Horizontal Pod Autoscaling) due to the need to obtain buffer metrics, as per the approach mentioned above.
However, we discovered that the 'buffer-metrics-sidecar' container does not provide options to configure CPU and memory requests and limits.

This is our pod describe info .
```
   buffer-metrics-sidecar:
    Container ID:  containerd://
    Image:         ghcr.io/kube-logging/node-exporter:v0.6.1
    Image ID:      ghcr.io/kube-logging/node-
    Port:          9200/TCP
    Host Port:     0/TCP
    Args:
      --startup
      ./bin/node_exporter --web.listen-address=:9200 --collector.disable-defaults --collector.filesystem
    State:          Running
      Started:      Tue, 13 Jun 2023 06:42:02 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /buffers from logging-operator-logging-fluentd-buffer (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g6644 (ro)
```
   
Is there anyone who has encountered a similar issue or can provide some suggestions?

https://github.com/kube-logging/logging-operator/blob/e183d85815b3111da679704101a3c5b7f6d28b02/pkg/resources/syslogng/statefulset.go#L264

Maybe we can add config for Resource

**Comment by pepov** [comment]
Thanks for reporting, yes we should make this configurable.

**Comment by cbuto** [comment]
@pepov I opened a [PR](https://github.com/kube-logging/logging-operator/pull/1426) that should resolve this, let me know what you think!

**Comment by aslafy-z** [comment]
Please make it configurable so I can remove CPU limits. Thank you
