### ISSUE TITLE
[QUESTION] how to update kafka2 to rdkafka

### ISSUE THREAD

**Issue by withlin** [kube-logging/logging-operator#1373]
kube-logging version: 3.17.0
k8s version: 1.26

fluent-plugin-kafka version: 0.17.5

but fluentd connect kafka error: `Cloud not connect  to any of the seed brokers: xxx:9999,xxx:9999,xxx:9999,Conection error EOFError: EOFError`

so i check the fluent-plugin-kafka docs:

https://github.com/fluent/fluent-plugin-kafka#output-plugin
> This kafka2 plugin is for fluentd v1 or later. This plugin uses ruby-kafka producer for writing data. If ruby-kafka doesn't fit your kafka environment, check rdkafka2 plugin instead. This will be out_kafka plugin in the future.

https://github.com/zendesk/ruby-kafka#compatibility

default config
```
<label @06cb8f659345bc35696661e33ae28ac2>
  <match **>
    @type kafka2 --> rdkafka

```

I read the kube-logging document and did not find how to update this type to rdkafka

**Comment by withlin** [comment]
@pehlert cc

**Comment by withlin** [comment]
@pepov  cc

**Comment by pepov** [comment]
You can open a pull request against the master branch and then we can backport it to 3.17. 

You have to make changes here:
- https://github.com/kube-logging/logging-operator/blob/master/pkg/sdk/logging/model/output/kafka.go#L143
- https://github.com/kube-logging/logging-operator/blob/master/pkg/sdk/logging/model/output/kafka_test.go#L41
