### ISSUE TITLE
With incorrect creds for elasticsearch(opensearch) in specific namespace, fluentd stops writing logs in the entire cluster.

### ISSUE THREAD

**Issue by dtoporin** [kube-logging/logging-operator#1377]
**Describe the bug**:
I have multiple namespaces in cluster and multiple indices in elasticsearch(opensearch) for each namespace with different users/pass credentials.
If you specify the wrong login or password for elastic in secret in specific namespace, then fluentd cannot send logs of all pods in cluster. It only helps to remove the wrong secret and restart all fluentd pods

**Expected behaviour**:
Wrong credentials not affected to all cluster 

**Steps to reproduce the bug**:
1. Create Secret with login/password for es in ns A
2. Create Flow  in ns A
3. Create Output  in ns A
4. Logs are written to the index A
5. Create Secret with login/password for es in ns B
6. Create Flow  in ns B
7. Create Output  in ns B
8. Logs are written to the index B
9. All logs writes to es indices
10. Create Secret with wrong login/password for es in ns C
11. Create Flow  in ns C
12.  Create Output  in ns C
13. All logs stop being written to the all indices

**Environment details**:
- Kubernetes version (e.g. v1.25.2): v1.17.5 - v1.25.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): NA
- logging-operator version (e.g. 2.1.1): all versions
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
On one hand this is not an issue with the logging operator as far as I understand it. On the other hand we are working on giving fluentbit the ability to send logs to different fluentd endpoints based on what namespace those logs are generated.

**Comment by pepov** [comment]
There is a new feature to start the configcheck pod with a timeout, which might help in this case since AFAIK the elasticsearch plugin will try to connect on startup.

https://kube-logging.dev/docs/whats-new/#timeout-based-configuration-checks
