### ISSUE TITLE
Refuse to reconcile multiple logging resources with the same loggingRef

### ISSUE THREAD

**Issue by pepov** [kube-logging/logging-operator#1386]
**Describe the bug**:
The behaviour for the logging operator is unpredictable if there are multiple logging resources using the same loggingRef. (A logging resource without an explicit logging ref set is considered the default and should be unique as well)

**Expected behaviour**:
The logging operator should refuse to reconcile such a resource. It should update the logging resource status so the the user know what's wrong. Ideally the logging operator should have an admission webhook to reject such a second logging resource with the same ref.

**Steps to reproduce the bug**:
Anyone can create two logging resources without a logging ref set on either of those, but that should be avoided.

/kind bug

**Comment by y-eight** [comment]
The same issue seems to occur if loggingRef is not set in different logging resources as well. FluentbitAgents dose not have a loggingRef set.

When reconciling the fluentbits from [loggingResources](https://github.com/kube-logging/logging-operator/blob/4.2.2/controllers/logging/logging_controller.go#L209) (FluentbitAgent List) all fluentbits that have an empty loggingRef in FluentbitAgent CR will be created, even if they are not part of the logging resource.

LoggingRed from FluentbitAgentList are compared [here](https://github.com/kube-logging/logging-operator/blob/4.2.2/pkg/resources/model/repository.go#L296)

Debugged with @eumel8

**Comment by pepov** [comment]
I'm not sure I understand the problem statement here.

If there is no loggingRef defined on the resources, then all resources (Flow,Output,ClusterFlow,ClusterOutput,FluentbitAgent) will be considered as part of the logging resource that has no loggingRef defined either. Now if there are more than one logging resources defined with an empty loggingRef, than all Flow,Output,ClusterFlow,ClusterOutput,FluentbitAgent resources  will be considered part of all these loggings. This is expected and the root cause is still the same: the logging operator allows multiple logging resources with the same loggingRef.

Putting the fluentbit spec back into the logging resource does not solve this problem, it's still a totally invalid use case. Please *do not* use multiple logging resources without a uniq loggingRef!

Probably you are aware, but also please note there is a bug that has just been reported: https://github.com/kube-logging/logging-operator/issues/1388

**Comment by pepov** [comment]
since this can be a breaking change, first we only introduce a deprecation notice
