### ISSUE TITLE
FluentbitSpec crd inconsistency

### ISSUE THREAD

**Issue by jouve** [kube-logging/logging-operator#1388]
**Describe the bug**:

in FluentbitSpec crd, the loggingRef field is named ` LoggingRef` (capital L)
this is inconsistent with the other crds.
  
loggingRef (lowercase l) does not generate any validation error, but it does nothing.

**Expected behaviour**:
it's named `loggingRef`  (consistent with all crds) or it generates a validation error when spelled with the lowercase l.

**Steps to reproduce the bug**:
see here : https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#fluentbitspec-loggingref

**Additional context**:

**Environment details**:
fluentbitagents.logging.banzaicloud.io v1beta1
chart version logging-operator-4.2.3 
appVersion: 4.2.2

/kind bug

**Comment by pepov** [comment]
This part of the CRD left untested, will fix it ASAP
