### ISSUE TITLE
Replace watchNamespaces and watchNamespaceSelector by watchNamespaceSelectors

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1394]
Deprecate `watchNamespaces` and encourage users to use the [`kubernetes.io/metadata.name` label (available since 1.22)](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling) to select namespaces by name. `watchNamespaceSelectors` will be added to support a list of selectors instead of a single selector as `watchNamespaceSelector` does.

Deprecate `watchNamespaces` and `watchNamespaceSelector` and mark for removal for  next major.

_Originally posted by @aslafy-z in https://github.com/kube-logging/logging-operator/pull/1392#issuecomment-1648323722_

**Comment by pepov** [comment]
to be fair, in a new API I would consider the selector-only option
