### ISSUE TITLE
Issue with PSPs handling when upgrading to 4.3 on Kubernetes 1.26

### ISSUE THREAD

**Issue by Roberdvs** [kube-logging/logging-operator#1428]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:

When upgrading from 4.2 to 4.3 on an EKS 1.26 cluster, the following error appears, seemingly due to the usage of `policy/v1beta1` APIs for working with PodSecurityPolicies that were removed in Kubernetes 1.25

<details>
<summary>Error log on logging-operator 4.3</summary>

> {"level":"error","ts":"2023-08-10T15:41:34Z","msg":"Reconciler error","controller":"logging","controllerGroup":"logging.banzaicloud.io","controllerKind":"Logging","Logging":{"name":"logging-operator"},"namespace":"","name":"logging-operator","reconcileID":"c7bf25c7-33f0-43de-88da-64eedf08c769","error":"**failed to reconcile resource: failed to delete resource: getting resource failed: failed to get API group resources: unable to retrieve the complete list of server APIs: policy/v1beta1: the server could not find the requested resource**","errorVerbose":"failed to get API group resources: unable to retrieve the complete list of server APIs: policy/v1beta1: the server could not find the requested resource\ngetting resource failed\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).delete\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.30.0/pkg/reconciler/resource.go:651\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.30.0/pkg/reconciler/resource.go:523\ngithub.com/kube-logging/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/usr/local/src/logging-operator/pkg/resources/fluentd/fluentd.go:124\ngithub.com/kube-logging/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/usr/local/src/logging-operator/controllers/logging/logging_controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to delete resource\nfailed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}

</details>

As a workaround for anyone else encountering this, you can set the environment variable `PSP_ENABLED=0`.

It might be a good idea to automatically add the environment variable to the Deployment when using the Helm chart, the same way that [PSPs are ignored](https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/templates/psp.yaml#L1) if the cluster lacks the API.

**Expected behaviour**:

**Steps to reproduce the bug**:
- I wasn't able to reproduce it on a fresh kind 1.26 cluster, only happened after upgrading from 4.2 on one of our testing clusters so it might be due to something carried over from previous versions installations.

**Additional context**:
Kubernetes API removals: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.26
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 4.3.0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):

<details>
<summary>Error log on logging-operator 4.3</summary>

> {"level":"error","ts":"2023-08-10T15:41:34Z","msg":"Reconciler error","controller":"logging","controllerGroup":"logging.banzaicloud.io","controllerKind":"Logging","Logging":{"name":"logging-operator"},"namespace":"","name":"logging-operator","reconcileID":"c7bf25c7-33f0-43de-88da-64eedf08c769","error":"**failed to reconcile resource: failed to delete resource: getting resource failed: failed to get API group resources: unable to retrieve the complete list of server APIs: policy/v1beta1: the server could not find the requested resource**","errorVerbose":"failed to get API group resources: unable to retrieve the complete list of server APIs: policy/v1beta1: the server could not find the requested resource\ngetting resource failed\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).delete\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.30.0/pkg/reconciler/resource.go:651\ngithub.com/cisco-open/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/cisco-open/operator-tools@v0.30.0/pkg/reconciler/resource.go:523\ngithub.com/kube-logging/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/usr/local/src/logging-operator/pkg/resources/fluentd/fluentd.go:124\ngithub.com/kube-logging/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/usr/local/src/logging-operator/controllers/logging/logging_controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to delete resource\nfailed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}

</details>

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
hey @Roberdvs ! thanks for reporting!

It should only happen on K8s version 1.24 and lower, see:
https://github.com/kube-logging/logging-operator/blob/4.3.0/main.go#L241

can you verify your test clusters weren't older than 1.25?

**Comment by oschira** [comment]
I'm having the same issue, on a fresh 1.26 cluster.

**Comment by pepov** [comment]
@oschira are you also running on eks? If the server version of eks produces a different result than we expect, I guess we should switch to listing api resources and disable psp-s based on that.

**Comment by sagikazarmark** [comment]
I have the same problem on EKS 1.27.
