### ISSUE TITLE
1) input tails (fluent-bit) causing logs to stop being generated entirely and 2) buffers not being filled up

### ISSUE THREAD

**Issue by dariuslwh95** [kube-logging/logging-operator#1433]
hello, I have been facing some issues configuring the logging operator specifically  1) input tails (fluent-bit) causing logs to stop being generated entirely and 2) buffers not being filled up. My environment is disconnected openshift.  I have installed the operator CRDs from the official helm chart. 
I have a clusterflow, clusteroutput on my cluster as well which sends log to kafka, adding of input tails as per the below stops logs from being generated entirely and  my /buffer does not seem to be filling up despite debugging the collector pods to check. 
I have to admit i'm quite new to using helm and k8s and in general and have been very confused as to how to edit the fluentbit.conf file / my logging operator configuration.

What steps can I take to solve these 2 issues?  And what would be the best practice of adjusting configurations using helm? would it be editing the kind: logging resource or otherwise?
Charts: https://github.com/kube-logging/logging-operator/tree/master/charts/logging-operator

**my logging operator:**
`||apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
spec:
...
  fluentbit:
    bufferStorage:
      storage.path: /buffers
    # inputTail:
    #   Path: /var/log/containers/*.log
    #   Path: /var/log/audit/kube-apiserver/*.log
    #   Path: /var/log/audit/oauth-apiserver/*.log
    #   Path: /var/log/audit/openshift-apiserver/*.log
    security:
      securityContext:
        privileged: true
    image:
      repository: <private repo>
      tag: 1.9.5-debug||`

**my fluentbit.conf file:**
`||[SERVICE]
    Flush        1
    Grace        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    Coro_Stack_Size    24576
    storage.path  /buffers

[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    DB.locking  true
    Mem_Buf_Limit  5MB
    Parser  cri
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*

[FILTER]
    Name        kubernetes
    Buffer_Size  0
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  On
    Use_Kubelet  Off

[OUTPUT]
    Name          forward
    Match         *
    Host          ocp-fluentbit-logging-root-fluentd.fluentbit.svc.cluster.local
    Port          24240
    
    Retry_Limit  False||`

Logs from my collector pods
Fluent Bit v1.9.5
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/08/15 07:46:58] [ info] [fluent bit] version=1.9.5, commit=9ec43447b6, pid=1
[2023/08/15 07:46:58] [ info] [storage] version=1.2.0, type=memory+filesystem, sync=normal, checksum=disabled, max_chunks_up=128
[2023/08/15 07:46:58] [ info] [storage] backlog input plugin: storage_backlog.1
[2023/08/15 07:46:58] [ info] [cmetrics] version=0.3.4
[2023/08/15 07:46:59] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 95.4M
[2023/08/15 07:46:59] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2023/08/15 07:46:59] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2023/08/15 07:46:59] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2023/08/15 07:46:59] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2023/08/15 07:46:59] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2023/08/15 07:46:59] [ info] [sp] stream processor started
[2023/08/15 07:46:59] [ info] [input:tail:tail.0] inotify_fs_add(): inode=107293714 watch_fd=1 name=/var/log/containers/dns-default-vkvtl_openshift-dns_dns-3105f9d30d6ffcc83f8a6f24e6052d63cda486d5e14babd193d0a039c5b7c9bb.log
[2023/08/15 07:46:59] [ info] [input:tail:tail.0] inotify_fs_add(): inode=107430649 watch_fd=2 name=/var/log/containers/dns-default-vkvtl_openshift-dns_dns-48d5869d06a665154b9a743df42e7f60b7837384a5c9eb8831896bfc0db85efd.log

**Comment by dariuslwh95** [comment]
kubernetes version: 1.25
logging-operator version: 1.95-debug
helm chart version: 3.17.10

**Comment by aslafy-z** [comment]
@dariuslwh95 I would recommend upgrading to fluentbit 2.x. I had similar issues with the 1.x series and there were tons of reports on the fluentbit repository.
The only workaround I found was regular restarts of the fluentbit agents.

**Comment by vwbusguy** [comment]
I'm still setting this happen as of fluent-bit 2.10.  I had also set `storage.type: filesystem` for InputTail, but it doesn't appear to actually set this in the fluent-bit.conf in the configMap, so I'm wondering if that setting might be broken, so it's defaulting to the in memory buffer which is getting overrun.

**Comment by pepov** [comment]
Please note that it is an old version and we are committed to support the last stable version only which is 4.4

As far as we are concerned rancher is not commited to upgrading the logging operator, but we have written a blog post on how you can upgrade your rancher based logging app, see: https://axoflow.com/get-the-latest-logging-operator-in-rancher/

@dariuslwh95 the chart you linked is the latest chart version which is very different from the 3.17 version.

On the other hand I wouldn't recommend to configure the logging resource from the chart. There is limited support to do that, but I would recommend putting the logging manifests into your own chart templates and only depend on the logging operator chart to install the operator itself. For example you wouldn't install cert-manager certificates with the cert-manager chart, would you?

If you insist on using the chart then you can use the `logging` field to configure the logging resource and `logging.fluentbit` to configure the fluentbit spec, see:
- https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/templates/logging.yaml
- https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/templates/logging_fluentbit.yaml

**Comment by pepov** [comment]
If you want to have a chat please reach out over the project discord: https://discord.gg/sXFdDKEKK8
