### ISSUE TITLE
create fluentd as deployment

### ISSUE THREAD

**Issue by zhj-hx** [kube-logging/logging-operator#1471]
The statefulset type causes pvc > 2 where sts.replicas > 2 . If the deployment object is used, one pvc can be shared.

**Comment by pepov** [comment]
Is that an environmental constraint or do you see some benefit by sharing a single pvc. Without a valid use case I don't think it would worth implementing that use case. 

A few reasons against:
- AFAIK most cloud providers do not support readwritemany out of the box
- How do you write automation to drain the buffers of a scaled down worker? Currently we can easily detect orphan PVCs and start drainer jobs, but I don't see a good option to do that for deployment replicas.

**Comment by zhj-hx** [comment]
This is a problem I encountered. I want to improve performance through multiple instances of fluentd, but multiple pvc will cause the collected service logs to be scattered to multiple filesystem directories.
