### ISSUE TITLE
The Fluentd configchecker labels are not configurable

### ISSUE THREAD

**Issue by blaivs** [kube-logging/logging-operator#1497]
**Is your feature request related to a problem? Please describe.**
Problem: When running the logging-operator in an istio enabled namespace, the fluentd-configcheck never transitions to a Completed state but stays in Running. This happens because Istio injects a sidecar that stays running thereby preventing the pod from completing. Before it could be disabled using annotations (see [related issue ](https://github.com/kube-logging/logging-operator/issues/462)), but now this is deprecated and should be done usings labels. Right now, also, if you use the fluentd labels field, it adds labels to both fluentd and configchecker, which feels a bit weird. 

**Describe the solution you'd like**
Being able to add labels specifically to configchecker.

**Comment by kristofgyuracz** [comment]
Hi,

This is already solved in https://github.com/kube-logging/logging-operator/pull/1449, and will be released with version 4.4.0.

**Comment by blaivs** [comment]
Oh, thanks @kristofgyuracz did some search but couldn't find it. Closing this issue then ❤️

**Comment by kristofgyuracz** [comment]
@blaivs https://github.com/kube-logging/logging-operator/releases/tag/4.4.0
