### ISSUE TITLE
ClusterOutput is running even with the wrong credentials.

### ISSUE THREAD

**Issue by BishowShrestha50** [kube-logging/logging-operator#1508]
**Describe the bug**:
We have passed the wrong credentials while passing the logs to the aws, cloudwatch, etc. But the cluster output/output doesn't show any errors while passing wrong credentials. The error is only shown in fluentd logs. Can the error message be shown if the logging operator is unable to connect with AWS, cloudwatch, or another provider?

**Expected behaviour**:
While passing the wrong credential while creating clusteroutput/output the clusteroutput should show the error. The error is only shown on fluentd logs. I need to show the error message if the logging operator is unable to connect with AWS, cloudwatch, or another provider in my application. I have difficulties showing the error message if the logging operator cannot connect with the aws or another provider in my application. As I cannot show the error by filtering the logs from fluentd.

**Environment details**:
- Kubernetes version (e.g. v1.15.2):v1.25.12
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE, etc):
- logging-operator version (e.g. 2.1.1):3.17.10
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: Logging CRD v1beta1

/kind bug

**Comment by pepov** [comment]
There is no method currently to highlight the fact that fluentd cannot connect to an output in the output status directly. However you can use the timeout based configcheck strategy that will at least prevent the configuration to take effect and you can understand the issue from the configcheck pod output directly.

See an example [here](https://github.com/kube-logging/logging-operator/pull/1431/files#diff-e8d9770dad9c6c99647b722d7d493170f0bd5f22e25b1d0f42cc67bfc3e89020R6) or in the latest release update: https://kube-logging.dev/docs/whats-new/

Note: you have to upgrade to 4.4 to have this

**Comment by BishowShrestha50** [comment]
I want to contribute in the code and create the method that will update the status of output to false if the fluentd have errors while passing wrong credentials. Are there any contributing guides or guidelines for this repo as I will be droping a PR.

**Comment by pepov** [comment]
Please join our discord to have a discussion about the implementation plan first: https://discord.gg/NAuSQUAdF9
