### ISSUE TITLE
logging ressource globalFilters into globalFiltersPre and globalFiltersPost

### ISSUE THREAD

**Issue by genofire** [kube-logging/logging-operator#1514]
**Is your feature request related to a problem? Please describe.**
the CRD Logging has the `globalFilters` entries.
But some filters want to be run, after the ClusterFlow/Flow has run.
e.g.:
 - geoip if ip.field
 - adding records with environames
 - dedot but that filter could be better placed direct infront of a ClusterOutput/Output

For safe (that a Flow-Author could not overwrite fields)

**Describe the solution you'd like**
has `globalFilterPost: []`

**Describe alternatives you've considered**
ClusterOutput/Output has (also) `globalFilters`

**Comment by genofire** [comment]
that is sad, that this issue was closed without an comment.

ping @pepov

**Comment by pepov** [comment]
I beleive that should already be possible by using the relabel output

**Comment by pepov** [comment]
https://kube-logging.dev/docs/configuration/plugins/outputs/relabel/

**Comment by pepov** [comment]
@genofire can you check if relabel can used for this?
