### ISSUE TITLE
support for fluentd to scrape and ship metrics 

### ISSUE THREAD

**Issue by xinity** [kube-logging/logging-operator#1572]
i've looked at the fluentd documentation and it seems we are able to use in input definition which will let fluentd scrape prometheus endpoints and ship them where ever needed:
https://docs.fluentbit.io/manual/pipeline/inputs/prometheus-scrape-metrics

is there a way to configure this behavior using logging-operator CRDs i've looked at the documentation but maybe i've missed something ?

**Comment by pepov** [comment]
Scraping metrics with the current implementation of the logging operator is not planned, neither with the collector (fluentbit) or the aggregators (fluentd/syslog-ng).

What is planned though is to introduce a new architecture, where multi-tenancy and routing are separated from enrichment and forwarding. In that new architecture we are going to utilise open-telemetry which is going to support the collection and forwarding of metrics natively.
