### ISSUE TITLE
Stuck of logging operator

### ISSUE THREAD

**Issue by ErikRosic** [kube-logging/logging-operator#1580]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
The problem is that if at least one of the threads is faulty, the logging operator gets stuck and does not continue updating other resources. Therefore, the development of one feature may not be deployed due to the development of another feature. Additionally, this freeze is invisible. Pod of the frozen logging operator is in the green Running state.

**Expected behaviour**:
The logging operator does not display any errors in the logs.
1.) set a non-existent output to the first Flow.
2.) set a non-existent output to the second Flow.
3.) change the number of fluentd replicas in the Logging resource.
4.) The number of replicas for fluentd will change.
5.) The logging operator indicates that there is no output for the first Flow.

**Steps to reproduce the bug**:
Prerequisites: The logging operator does not display any errors in the logs.
1.) set a non-existent output to the first Flow.
2.) set a non-existent output to the second Flow.
3.) change the number of fluentd replicas in the Logging resource.
4.) The number of replicas for fluentd will not change.
5.) The logging operator indicates that there is no output for the first Flow.
6.) fix the output for the first Flow.
7.) Logging operator indicates that there is no output for Flow types.
8.) We will fix the output for Flow types.
9.) The number of replicas for fluentd will change.
10.) The logging operator does not display any errors in the logs.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.26.8 
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): 
- logging-operator version (e.g. 2.1.1): 3.17.9
- Install method (e.g. helm or static manifests): HELM
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
related to https://github.com/kube-logging/logging-operator/issues/1567

**Comment by pepov** [comment]
Please use `skipInvalidResources` in the logging spec to let the operator skip these errors.

**Comment by sebastiangaiser** [comment]
@pepov can you maybe trigger a release for this. Would be great to use it via the chart. Or is there already an ETA for a new release?

**Comment by pepov** [comment]
This is not a new feature, available for a while now. However if you need the release for a different reason I just triggered an rc yesterday: https://github.com/kube-logging/logging-operator/releases/tag/4.6.0-rc.0
