### ISSUE TITLE
Helm installing Logging Operator in k8s version 1.25 and above.

### ISSUE THREAD

**Issue by dipak140** [kube-logging/logging-operator#1625]
**Describe the bug**:
While trying to install logging-operator using helm, i am getting the error: **UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "psp.logging-operator" namespace: "logging" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"**

k8s version client side: 1.27
k8s version server side: 1.25

**Expected behaviour**:
logging-operator should be installed

**Steps to reproduce the bug**:
k8s version: 1.25
run: helm upgrade --install --wait --create-namespace --namespace logging logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator --version=4.5.0

**Additional context**:
This can be related to k8s removing PodSecurityPolicy starting for k8s version 1.25 and above.

**Environment details**:
- Kubernetes version: 1.25
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 4.5.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): [helm.txt](https://github.com/kube-logging/logging-operator/files/13749567/helm.txt)
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: None

/kind bug

**Comment by kristofgyuracz** [comment]
Hi @dipak140,
Thanks for submitting this issue.
I've tried to reproduce the issue, a clean installation on a K8s cluster (1.25+) worked fine.
Did you have a previous deployment of logging-operator on your cluster?

If you were actually upgrading a deployment, that was installed on an older K8s release that was upgraded at some point, the root cause can be the Helm upgrade process (https://github.com/helm/helm/issues/11287).

**Comment by pepov** [comment]
based on a community discussion this can be solved using https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards#cleaning-up-releases-after-a-kubernetes-v125-upgrade 

https://discord.com/channels/1082023686028148877/1082624361963454545/1187721882439524412
