### ISSUE TITLE
Developer Contribution

### ISSUE THREAD

**Issue by busyboy77** [kube-logging/logging-operator#1626]
Hi,

I have a number of developers in Java + Go Lang and I want to contribute to this project by dedicating 1 of these developers. Can someone please guide what is the way forward to onboard a developer for logging-operator and start contributing.

Regards,
Samunder Khan
Gradus PK
gradus.pk

**Comment by OverOrion** [comment]
Hey there @busyboy77,

Thank you for showing interest in contributing to the logging operator project!
The [README.md ](https://github.com/kube-logging/logging-operator/blob/master/README.md) should give you a high level overview of the project.

I think the [CONTRIBUTING.md](https://github.com/kube-logging/logging-operator/blob/master/CONTRIBUTING.md) should give you the _how_  to work and going through the [currently open issues](https://github.com/kube-logging/logging-operator/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-desc) should give you the _what_ to work on.

See the documentation's for developers part:
https://kube-logging.dev/docs/developers/

Also a link to the Discord channel: https://discord.gg/eAcqmAVU2u

**Comment by pepov** [comment]
@busyboy77 that sounds awesome! Please join our discord server where we have a contributors channel to discuss how to get started, just let me know once you are there and will add you!
