### ISSUE TITLE
fluend multiline support

### ISSUE THREAD

**Issue by g-traveller** [kube-logging/logging-operator#1662]
Hi,

I am writing a multline paser and send to ElasticSearch, however, it is not working, logs is seperated multiple lines:

- Container logs: in node (/var/log/containers/xxx.log)
![image](https://github.com/kube-logging/logging-operator/assets/27939320/7b3a6169-e470-42ae-b62d-354444660872)

- Logging operator parser
![image](https://github.com/kube-logging/logging-operator/assets/27939320/66b7e0ff-abad-4a0a-be01-4bd534e4c115)

- Finally, logs is seperated multiple lines

Could you please help to check?
Thanks

**Comment by OverOrion** [comment]
Hey there @g-traveller,

I suggest you to have a look at fluentd's docs: https://docs.fluentd.org/parser/multiline#java-stacktrace-log

Could you please also share your logs / config snippets as text?
