### ISSUE TITLE
ability to change repository path for the buffer-metrics-sidecar

### ISSUE THREAD

**Issue by ajchiarello** [kube-logging/logging-operator#1703]
We would like to be able to change the repository path for the buffer-metrics-sidecar image, so that we can pull it via our proxy cache. I found how to do this for the config-reloader image (logging.fluentd.configReloaderImage.repository), but I don't see a corresponding way to do it for the metrics sidecar

**Comment by pepov** [comment]
@ajchiarello it's `logging.fluentd.bufferVolumeImage`
