### ISSUE TITLE
Add option to control if ClusterOutput can be used from namespaced Flows or not

### ISSUE THREAD

**Issue by xhejtman** [kube-logging/logging-operator#1709]
**Is your feature request related to a problem? Please describe.**
Currently, cluster administrators can create Cluster Flows and Cluster Outputs. Any user can send Flow to the Cluster Output spamming admins outputs with his/her logs.

**Describe the solution you'd like**
A simple flag for the operator config so that user Flow cannot reference Cluster Output.

**Comment by pepov** [comment]
Thanks @xhejtman ! 

I would suggest having a flag on the ClusterOutput and SyslogNGClusterOutput CRDs instead so that admins can decide whether they want to share or hide one-by-one instead of doing it globally. Does it make sense?

**Comment by xhejtman** [comment]
Yes, makes sense perfectly

**Comment by sebastiangaiser** [comment]
As a sidenote. We archived this by a Kyverno Policy but I would also be interested in this feature.

**Comment by pepov** [comment]
planned for the next release milestone: https://github.com/kube-logging/logging-operator/milestone/27
