### ISSUE TITLE
HostTailer Upgrade Strategy override

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#1721]
**Is your feature request related to a problem? Please describe.**
It may take time to rollout hosttailer daemonsets in big clusters.

**Describe the solution you'd like**
I would like to customize the upgrade strategy. 

**Describe alternatives you've considered**
Re-implement the DS myself.

**Comment by pepov** [comment]
Whoever is able to pick this up I can give guidance on how we do incorporate a full daemonset override type that is a generic solution for most customization problems.
