### ISSUE TITLE
Chain multiple parsers with FluentbitAgent to process cri logs

### ISSUE THREAD

**Issue by cataclyst23** [kube-logging/logging-operator#1784]
**Is your feature request related to a problem? Please describe.**

Hi! The problem I'm trying to solve describes a pretty common case - collect the _cri_-formatted logs from containers, then index the collected fields within the _log_ field so that I can work with them in Elasticsearch. The problem is described in this article : https://yossicohn.medium.com/fluent-bit-configuration-for-kubernetes-with-cri-38ea88ad6a7c.

**Describe the solution you'd like**

The solution is pretty straight forward using the native Fluentbit configs, but I'd like to reach the same state using a FluentbitAgent CR.
My problem is that the solution would need multiple parsers to be applied sequentially (first the _cri_ parsing, then parsing the _message_ field as a JSON object), but I could only find the _inputTail.Parser_ parameter that I could work with and not sure if there's a way to use parser typed filters, since I also only found the _filterModify_ field in the documentation. I've tried to use custom parsers as well relying on the _Decode_Field_As_ parameter, but it doesn't seem to work.
The logs are not multiline either, so it's a pretty basic scenario. If there's already a way to do this, please let me know because I couldn't find it yet.

**Describe alternatives you've considered**

I know that there's a more refined way to perform parsing using the _Flow/ClusterFlow_ objects, but as far as I know that's for configuring FluentD instance and I'd prefer to do it on Fluentbit's side.

**Additional context**

A sample log after using the built-in _cri_ parser under _spec.inputTail_:
`{
    "stream":"stdout",
    "logtag":"F",
    "log":{
        "level":"info",
        "origin":{
            "function":"<computed>",
            "file":{
                "name":"/app/node_modules/.../logger.js",
                "line":101
            }
        }
    },
    "timestamp":"2024-07-25T13:52:00.432Z",
    "message":"Original log message",
    "ecs":{"version":"1.5.0"},
    "service":{"name":"test","version":"v0.1"},
    "labels":{"command":"./scripts/test.sh"},
    "tags":[],
    "kubernetes":{ ... },
}`

**Comment by pepov** [comment]
@cataclyst23 This our recommended workardound for this problem at the moment:
https://github.com/kube-logging/logging-operator/blob/master/config/samples/containerd-merge-log.yaml

**Comment by pepov** [comment]
Also, with 4.9 there is a single flag to enable this behaviour: `enableDockerParserCompatibilityForCRI`

https://github.com/kube-logging/logging-operator/pull/1793
