### ISSUE TITLE
Allow for configuring mulitple Logging resources with FluentdConfigs in the same namespace

### ISSUE THREAD

**Issue by joshmeranda** [kube-logging/logging-operator#1797]
**Is your feature request related to a problem? Please describe.**

When trying to configure `Fleuntd` for multiple `Logging` resources in a `logging` namespace the user can only configure each within [`LoggingSpec.fluentd`](https://kube-logging.dev/docs/configuration/crds/v1beta1/logging_types/#loggingspec-fluentd) or use the same [`FluentdConfig`](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentd_config_types/) for all `Logging` resources.

The inconsistency between the older `.spec.fluentd` configuration method and the newer `FleuntdConfig` method feels un-intuitive.

**Describe the solution you'd like**

Implement something like [`FluentBitSpec.loggingRef`](https://kube-logging.dev/docs/configuration/crds/v1beta1/fluentbit_types/#fluentbitspec-loggingref) to allow us to explicitly state which `FluentdConfig` is intended for which `Logging.`

**Describe alternatives you've considered**

**Additional context**

**Comment by pepov** [comment]
Hey @joshmeranda ! Thanks for bringing this up! You are right in that there is no loggingRef in the FluentdConfig resource, but it is for good reason. The purpose of the FluentdConfig resource is to let tenant users manage it themselves. This is described here:
https://github.com/kube-logging/logging-operator/blob/master/docs/standalone-aggregator-config.md

Also you should be able to use different FluentdConfig resources for each Logging resource. Put the FluentdConfig in the controlNamespace of the Logging resource and you should be good to go. Let me know if it doesn't work for you either and I will take a look.

**Comment by pepov** [comment]
Closing this as the only issue here was about inconsistent behaviour, however that behavior is intended and unavoidable.
