### ISSUE TITLE
Release notes shows wrong version in Install with helm

### ISSUE THREAD

**Issue by sebastiangaiser** [kube-logging/logging-operator#1852]
**Describe the bug**:
Release notes shows wrong version in `Install with helm` section in https://github.com/kube-logging/logging-operator/releases/tag/4.11.0:

```
helm install logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator --version=4.10.0
```

**Expected behaviour**:
Show correct version
```
helm install logging-operator oci://ghcr.io/kube-logging/helm-charts/logging-operator --version=4.11.0
```

/kind bug

**Comment by csatib02** [comment]
Thanks for reporting this, fixed!
