### ISSUE TITLE
Remove resource finalizers before terminating operator

### ISSUE THREAD

**Issue by mriley-mbgp** [kube-logging/logging-operator#1859]
**Is your feature request related to a problem? Please describe.**
For cluster consistency, we have developed a Helm chart to install the logging-operator as a dependency and deploy our configuration files tweaked as necessary. We have used the new recommended pattern of separate custom resources for the configuration by utilising `SyslogNGConfig` in our deployment, which adds a finalizer onto the matching `Logging` resource to prevent deletion of this resource.

```
Name:         dev-cluster-logging-agent
Namespace:
Labels:       app.kubernetes.io/instance=dev-cluster-logging
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=dev-cluster-logging
              app.kubernetes.io/version=0.2.4
              helm.sh/chart=mbgp-cluster-logging-0.1.0
Annotations:  fluentbit.io/exclude: true
              meta.helm.sh/release-name: dev-cluster-logging
              meta.helm.sh/release-namespace: logging
API Version:  logging.banzaicloud.io/v1beta1
Kind:         Logging
Metadata:
  Creation Timestamp:  2024-11-22T14:03:57Z
  Finalizers:
    syslogngconfig.logging.banzaicloud.io/finalizer
  Generation:        2
  Resource Version:  2339510619
  UID:               a59cea21-b4f8-4cb0-bed8-6bc0fea99392
Spec:
  Cluster Domain:  cluster.local.
  Config Check:
    Timeout Seconds:  10
  Control Namespace:  logging
Status:
  Config Check Results:
    6d39d335:             true
  Syslog NG Config Name:  dev-cluster-logging-agent
Events:                   <none>
```

When manually removing the `SyslogNGConfig` only, the finalizer is successfully removed by the logging operator off the `Logging` resource. When performing a Helm uninstall, the logging-operator terminates without removing finalizers, so the `Logging` resource is left dangling which can persist old configuration when deploying over the top of an old deployment. 

**Describe the solution you'd like**
It's hard to know exactly how one should proceed solution wise, but an idea might be to check for existing finalizers before termination of the logging operator and remove them. As the logging operator is the one that manages the allocation and checks around finalizers, if this resource doesn't exist, it will only cause dangling resources. This method could lead to an "at risk" period if the logging operator were to crash or be rescheduled, before returning them on next start up.

**Describe alternatives you've considered**
We cannot enforce ordering with a Helm uninstall, so cannot choose to remove the config ahead of other resources. Sub charts are supposed to be removed after the parent charts as they are dependencies for the parent chart, but even with this for the logging-operator, it appears we destroy the logging operator before the `SyslogNGConfig` finalizer is removed after that resource is deleted. As a result, even overlooking the maintenance burden of having a separate chart for the SyslogNGConfig, it is likely we still run into this problem.

For now, we have to remain with the inline `Logging` configuration as this doesn't produce a finalizer and allows us to clean up all resources as part of our deployment.

**Additional context**
We run a number of on premise Kubernetes clusters that we are standardising, hence our Helm chart installs for configuration. Whilst we do not require multi-tenancy features at present, this is an option we would like open to us in the future through the new configuration resource. At this time, the only way we can ensure full clean up through Helm is by using the inline logging configuration, so it is a blocker to retiring this method for us.

It is not entirely clear to me how other operators deal with problems of a similar nature, as I understand the need for finalizers to prevent accidental deletion of resources, so this proposed solution might not be the best way forward but I'm happy to feedback and understand suggestions.

This issue was originally [raised and discussed through the Slack channel](https://cloud-native.slack.com/archives/C06DW57NWSJ/p1732186336821579).

**Comment by csatib02** [comment]
Hi @mriley-mbgp,

Since the issue relates to Helm missing on deleting aggregator configs due to finalizers not getting deleted, I think we should start with adding [Helm-hooks](https://helm.sh/docs/topics/charts_hooks/), if that solves the problem in your use-case, I tihink this is resolved.

**Comment by csatib02** [comment]
@mriley-mbgp

FYI: #1873

**Comment by mriley-mbgp** [comment]
Thanks @csatib02, that should be enough to move past this issue.
