### ISSUE TITLE
The operator crashed when using flowconfigovverid in logging crd

### ISSUE THREAD

**Issue by rverma-jm** [kube-logging/logging-operator#420]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
 Created a logging crd as 

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: vpcflowlogs
  namespace: siem
spec:
  loggingRef: siem
  flowConfigOverride: |-
    <source>
      @type s3
      <web_identity_credentials>
        role_arn          ROLE_ARN #expected to get this from env variable
        role_session_name ROLE_SESSION_NAME
        web_identity_token_file AWS_WEB_IDENTITY_TOKEN_FILE
      </web_identity_credentials>
      s3_bucket jm-audit-logs
      s3_region ap-south-1
      add_object_metadata false
      store_as gzip
      format tsv
      <sqs>
        queue_name jm_audit_logs_vpcflowlogs
      </sqs>
    </source>
  enableRecreateWorkloadOnImmutableFieldChange: true
  fluentd:
    security:
      serviceAccount: fluentd
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  controlNamespace: siem
```
When created the above resource found that operator itself start crashing. 

**Expected behaviour**:
Operartor should not crash, infact it should submit status on crd with reason for invalidation.

**Environment details**:
- Kubernetes version v1.4
- Cloud-provider/provisioner EKS
- logging-operator version 3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): NA
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by envybee** [comment]
Hi, we are running into this issue as well. Wondering if there is any update? Thanks

**Comment by envybee** [comment]
It looks like it's running into a NPE or such here: https://github.com/banzaicloud/logging-operator/blob/3c9ab3f0390408914dd03f1941b3dc812a6958f9/pkg/resources/fluentd/outputsecret.go#L68
