### ISSUE TITLE
Operator does not check if nodeAgent(s) are removed when reconciling a CR of the same name

### ISSUE THREAD

**Issue by nickgerace** [kube-logging/logging-operator#725]
**Describe the bug**:
When upgrading a 3.9.4 chart with Windows nodeAgent(s) installed, if the nodeAgent has been removed from the Logging CR in-use, the operator will not clean up the existing nodeAgent(s). This behavior is most likely the same for Linux nodeAgents as well.

**Expected behaviour**:
Similar to removing a fluentbit field from a Logging CR and running `helm upgrade`, running `helm upgrade` after removing a nodeAgent should result in the deletion of that nodeAgent.

**Steps to reproduce the bug**:
1. Install the Logging Operator 3.9.4 chart with a Logging CR bundled (this needs at least one nodeAgent (this was only tested with Windows)
2. Delete nodeAgent from the Logging CR
3. Run `helm upgrade`
4. nodeAgent will not be deleted

**Additional context**:
The Logging CR was bundled with the chart when this issue was first encountered.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v.1.20.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): n/a
- logging-operator version (e.g. 2.1.1): 3.9.4
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): logs show no errors
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: Logging CRD v1beta1

/kind bug

**Comment by pepov** [comment]
We had some discussions internally, but not yet finalized on what should we do about this.

- We have an option to rewrite the reconciler core, which is a slightly bigger/riskier change and not yet put it on the roadmap.
- The other option is to implement a more specific check into the reconcile loop, that would notice the difference between the desired state and the actual nodeagent resources and removes them. The problem is, that since we don't remove an actual resource, but only an item in the list, the Kubernetes GC won't notice.

**Comment by nickgerace** [comment]
Thank you for looking into this @pepov! Either option would be suitable for us; we have a workaround at the moment as well via our documentation.

> The problem is, that since we don't remove an actual resource, but only an item in the list, the Kubernetes GC won't notice.
Is it an anti-pattern for the reconcile loop to have a "Delete If Exists" style of function? This function could be called when the difference between the desired state and the actual state check is trigged, and the nodeAgents being removed from the list are explicitly deleted.

**Comment by pepov** [comment]
> Is it an anti-pattern for the reconcile loop to have a "Delete If Exists" style of function? This function could be called when the difference between the desired state and the actual state check is trigged, and the nodeAgents being removed from the list are explicitly deleted.

Not an anti-pattern just not natively embedded into the controller-runtime tooling as far as we know. Client tools all do this slighlty differently. We have an approach for this, it just evolved after the logging operator core had been established so now we have to refactor a bit to have it.

By the way it works by grouping resources into components and adding a specific annotation to each resource on create/update. After reconciling a component we remove all the resources with matching annotations that are not included in the actual list of desired resources.

**Comment by nickgerace** [comment]
Thank you for the clarification on the deletion pattern for the operator. That makes sense to me!

> By the way it works by grouping resources into components and adding a specific annotation to each resource on create/update. After reconciling a component we remove all the resources with matching annotations that are not included in the actual list of desired resources.

Ah, this should work for us as another workaround. I'll try it, and see if we run into the same thing again (we shouldn't, from what I can see in the code). Thank you.

**Comment by ekhaydarov** [comment]
Seeing this issue as well. Not sure how to resolve this? or will there be a chart update that addresses this?

**Comment by pepov** [comment]
This is going to be officially supported in 4.3

**Comment by pepov** [comment]
NodeAgents are not going to be supported in the future and will be marked for deletion from the API in the next major release.
