### ISSUE TITLE
geoip_2_database  invalid

### ISSUE THREAD

**Issue by adou0510** [kube-logging/logging-operator#738]
fluentd  is use geoip2_database 
![企业微信截图_16209737867616](https://user-images.githubusercontent.com/66617271/118238402-0c245300-b4cb-11eb-9ac8-850e39d3fe63.png)

geoip_2_database   config   create geoip_2_database   Causes configuration failure
![企业微信截图_16209741445094](https://user-images.githubusercontent.com/66617271/118238387-075f9f00-b4cb-11eb-9251-9ce5dcc78374.png)
![企业微信截图_16209737957760](https://user-images.githubusercontent.com/66617271/118238393-09296280-b4cb-11eb-913a-216fec279c17.png)

**Comment by adou0510** [comment]
@ahma  yes, it does't work for me

**Comment by genofire** [comment]
could be solved also
