### ISSUE TITLE
tag_normaliser doesn't work,messages come without tagging

### ISSUE THREAD

**Issue by artemkrim** [kube-logging/logging-operator#741]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
tag_normaliser doesn't work when use regexep, messages come without tagging

**Environment details**:
- Kubernetes version: 1.19.0
- logging-operator version: 3.9.0
- Install method: helm

**config**
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: main-text
  namespace: logging-operator
spec:
  match:
    - select:
        namespaces:
          - ingress-nginx
          - cert-manager
          - teleport-agent
  filters:
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
    - parser:
        parse:
          type: multi_format
          patterns:
          - format: none
    - record_modifier:
        records:
          - application_name: ***
          - application: ***
          - cluster_name: ***
  globalOutputRefs:
    - ***

**Comment by mayrstefan** [comment]
I think we might see the same issue: we are using version 3.9.4 which comes with Rancher 2.5.8

Using one of the examples with a GELF output
`format: cluster1.${namespace_name}.${pod_name}.${container_name}` 
we receive a tag field with value 
`cluster1.{unknown}.{unknown}.{unknown}`

**Comment by pepov** [comment]
Unfortunately I don't have access to a rancher cluster, so it's not easy for me to reproduce. Can you give me a reproducible example that works on a minikube or kind installation?
