### ISSUE TITLE
A "key value pair" parser should exist

### ISSUE THREAD

**Issue by mkaiserincomm** [kube-logging/logging-operator#851]
**Is your feature request related to a problem? Please describe.**
A parser should exists which functions similar to "csv" or "tsv", but parses key value pairs instead.

**Describe the solution you'd like**
Parser "kvp" should exist

**Describe alternatives you've considered**
Parsing the logs at the logging target, undesirable since each logging target does this differently and some cannot do this.

**Comment by pepov** [comment]
this is unrelated to the logging operator. if fluentd supports such a plugin we can add a feature request to support it
