### ISSUE TITLE
fluentbit unable to connect to fluentd due to hostname mismatch

### ISSUE THREAD

**Issue by sstafford** [kube-logging/logging-operator#934]
**Describe the bug**:
When deploying a new instance of the logging operator, the fluentbit containers running on each node are failing to connect to the fluentd pod.  The errors in the fluentbit containers look like this:

getaddrinfo(host='default-logging-simple-fluentd.cattle-logging-system.svc.cluster.local', err=4): Domain name not found

**Expected behaviour**:
fluentbit containers should connect to the fluentd container and start sending log data.

**Steps to reproduce the bug**:
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm repo update
helm upgrade --install --wait --create-namespace --namespace cattle-logging-system logging-operator banzaicloud-stable/logging-operator
kubectl -n cattle-logging-system apply -f logging-cluster.yml

**Additional context**:
From what I can tell, the hostname of the fluentd container is actually "default-logging-simple-fluentd-0" and does not match the "default-logging-simple-fluentd" hostname that fluentbit is attempting to connect to.  Here is the command used to get the fluentd hostname:

kubectl -n cattle-logging-system exec --stdin --tty default-logging-simple-fluentd-0 -c fluentd -- hostname

**Environment details**:
- Kubernetes version (e.g. v1.15.2):  1.22.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):  Rancher on-premise
- logging-operator version (e.g. 2.1.1):  3.17.1
- Install method (e.g. helm or static manifests):  helm

Additional logs and config files are attached:

[logging_operator_support.tar.gz](https://github.com/banzaicloud/logging-operator/files/8143417/logging_operator_support.tar.gz)

/kind bug

**Comment by artemkrim** [comment]
fast fix
```
###logging-operator-logging
fluentbit:
  targetHost: logging-operator-logging-fluentd-0.logging-operator-logging-fluentd-headless.logging-operator.svc
```

**Comment by aslafy-z** [comment]
Is this still applicable with the latest releases?

**Comment by pepov** [comment]
this should work, I couldn't reproduce with the current chart (kube-logging/logging-operator v4.0.0) and log-generator image `ghcr.io/kube-logging/log-generator:v0.4.1`
