### ISSUE TITLE
Configcheck pods are not cleaned-up 

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/logging-operator#976]
**Describe the bug**:
Configcheck pods are not cleaned-up on success.

**Expected behaviour**:
Old succesful configcheck pods are deleted once the configuration is applied.
 
**Steps to reproduce the bug**:
- Deploy a Logging CR and an Output object. 
- Edit the Output object with a valid configuration.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.20.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- logging-operator version (e.g. 2.1.1): 3.17.3
- Install method (e.g. helm or static manifests): helm

**References**:
- https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/fluentd.go#L141
- https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/appconfigmap.go#L142

/kind bug

**Comment by aslafy-z** [comment]
Configcheck secrets are not cleaned up too. I have ~5000 useless secrets in my logging-operator namespace...

**Comment by pepov** [comment]
Can you help me with a configuration that could help me reproduce this issue?

**Comment by aslafy-z** [comment]
It looks like it's ok now. I'll reopen this issue if I found I'm still impacted. Thanks @pepov
