### ISSUE TITLE
logging rancher-logging-fluentd-configcheck-8c46b65d error

### ISSUE THREAD

**Issue by raoping2017** [kube-logging/logging-operator#992]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
2022-04-29 03:42:44 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="out_file: `/var/log/logging/file/a.202204290340_**.log` is not writable"

**Expected behaviour**:
a new flow and a new output created, yaml info:

output yaml:
 apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  creationTimestamp: "2022-04-29T01:46:48Z"
  generation: 1
  managedFields:
  - apiVersion: logging.banzaicloud.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:file:
          .: {}
          f:path: {}
    manager: agent
    operation: Update
    time: "2022-04-29T01:46:48Z"
  - apiVersion: logging.banzaicloud.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:active: {}
    manager: manager
    operation: Update
    time: "2022-04-29T01:46:48Z"
  name: nginx-out-file
  namespace: default
  resourceVersion: "219810"
  uid: 5284cc2d-a2f3-4dad-9958-6c139f29ec53
spec:
  file:
    path: /var/log/logging/file/${tag}
status:
  active: true

flow yaml:
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  creationTimestamp: "2022-04-29T03:42:42Z"
  generation: 1
  managedFields:
  - apiVersion: logging.banzaicloud.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:filters: {}
        f:globalOutputRefs: {}
        f:localOutputRefs: {}
        f:match: {}
    manager: agent
    operation: Update
    time: "2022-04-29T03:42:42Z"
  - apiVersion: logging.banzaicloud.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:active: {}
    manager: manager
    operation: Update
    time: "2022-04-29T03:42:42Z"
  name: nginx-flow-file
  namespace: default
  resourceVersion: "219811"
  uid: 591a5247-7541-45d7-a4ce-55d4f43e544c
spec:
  filters:
  - parser:
      parse:
        type: nginx
      remove_key_name_field: true
  globalOutputRefs: []
  localOutputRefs:
  - nginx-out-file
  match:
  - select:
      container_names:
      - nginx
      hosts:
      - rancher-srv
      labels:
        name: nginx
status:
  active: true

**Steps to reproduce the bug**:
a new rancher-logging-fluentd-configcheck-xxxxx pod created when a new flow created, and error as Describe the bug

**Environment details**:
rancher 2.6.3

/kind bug

**Comment by ahma** [comment]
@raoping2017 could you share us the logging-operator, fluend, fluentbit versions pls ?

**Comment by sureshgoli25** [comment]
We solved this problem by setting like below in values file of the logging chart provided by rancher in 2.6.3

```
loggingOverlay:
  spec:
    fluentd:
      fluentOutLogrotate:
        age: '10'
        enabled: true
        path: /buffers/logs/out
        size: '10485760'
      logLevel: debug

```
